name:                parse
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec 
- text-show
- mtl
- hint
- text
- megaparsec
- containers
- parser-combinators


ghc-options: [ -Wall , -Wcompat , -Widentities , -Wincomplete-record-updates , -Wincomplete-uni-patterns ,  -Wmissing-home-modules , -Wpartial-fields , -Wredundant-constraints ]

library:
  source-dirs: src

executables:
  parse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: [ -threaded , -rtsopts , -with-rtsopts=-N ] 
    dependencies:
    - parse

tests:
  parse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [ -threaded , -rtsopts , -with-rtsopts=-N ]
    dependencies:
    - parse
